### ISSUE TITLE
Can't get user information

### ISSUE THREAD

**Issue by nvhaiwork** [Utsav2/AndroidTradier#2]
...

**Comment by Utsav2** [comment]
Did you get it to work?

**Comment by nvhaiwork** [comment]
Yes, but with some modifies of code.
1: I must change UserClient(and some class) to public.
Without above change, when I call: client.user(watchlist..) eclipse will give error : UserClient is not visible
2: AccountClient
Change from:
requestUrl += BASE_URL + "/accounts/" + id;
To : 
requestUrl = BASE_URL + "/accounts/" + id;
Without above change, when you call accountClient.get...
so requestUrl is : nullhttps:/.....
and requestUrl  is static => when you call client(Tradier).getAccount in 2nd times, 
requestUrl  will be : nullhttps://api.tradier...https://api.tradier....

Please confirm about above change.
thanks!

**Comment by Utsav2** [comment]
I have fixed these errors. Thanks!

**Comment by nvhaiwork** [comment]
Can you take a look with Order class too?
And can you add some java doc for functions? 
Today I used Tradier.getAccount(id);
There is no document to tell me that "id" is account_number. So I passed id(returned from client.getUser),  and server always returns error. I just found that after goto website and read document of web api

**Comment by nvhaiwork** [comment]
Hey, MarketClient still no public. Please change it

**Comment by Utsav2** [comment]
I've changed it as well. As for the docs, the web API docs are pretty good. I think I should put a link to them in the readme if anyone has doubts

**Comment by nvhaiwork** [comment]
And another question is why need to set static for String requestUrl and final String BASE_URL.

P/s: i just wantto help you to make Android Traider api better. Please tell me if any inconvinient :D

Thanks for your api

**Comment by nvhaiwork** [comment]
Sorry again. But can you take a look with requestUrl of OrderClient.
About javadoc: it's ok :D. Web API doc are enough :D

**Comment by Utsav2** [comment]
Sure. I fixed that error. I set them static so there's no need to make multiple copies of those Strings, which would waste memory
