### ISSUE TITLE
Can't getQuote

### ISSUE THREAD

**Issue by nvhaiwork** [Utsav2/AndroidTradier#4]
String symbol = "AAPL";
        ArrayList<String> symbols = new ArrayList<String>();
        symbols.add(symbol);
        // symbols.add("T");
        mClient.market.getQuote(symbols, new Response.Listener<String>() {
            @Override
            public void onResponse(String response) {

```
            LogUtil.e("getQuote", response);
        }
    }, new Response.ErrorListener() {
        @Override
        public void onErrorResponse(VolleyError error) {

            displayOrderErrorMessage("");
        }
    });
```

This is my code and this is result:
[7282] BasicNetwork.performRequest: Unexpected response code 400 for https://api.tradier.com/v1/markets/quotes

Please help

**Comment by Utsav2** [comment]
Hey. You can see that the URL is fine, and for me the code works. I don't really know why it's going wrong for you.  You can see the MarketClient class to see how the String is being built up for the order
